version: '3.8'

services:
  dbproductividad:
    image: postgres:17-alpine
    container_name: dbproductividad
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - productivity-net

  redis:
    image: redis:7-alpine
    container_name: redisproductividad
    restart: always
    ports:
      - "6379:6379"
    networks:
      - productivity-net

  web:
    image: ghcr.io/byronmoreno/productividad:latest
    container_name: webproductividad
    restart: always
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dbproductividad:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - dbproductividad
      - redis
    networks:
      - productivity-net
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kanban.entrypoints=http"
      - "traefik.http.routers.kanban.rule=Host(`kanban.byronrm.com`)"
      - "traefik.http.middlewares.kanban-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.kanban.middlewares=portainer-https-redirect"
      - "traefik.http.routers.kanban-secure.entrypoints=https"
      - "traefik.http.routers.kanban-secure.rule=Host(`kanban.byronrm.com`)"
      - "traefik.http.routers.kanban-secure.tls=true"
      - "traefik.http.routers.kanban-secure.tls.certresolver=http"
      - "traefik.http.routers.kanban-secure.service=kanban"
      - "traefik.http.services.kanban.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik-public"

  celery_worker:
    image: ghcr.io/byronmoreno/productividad:latest
    container_name: celeryproductividad
    restart: always
    command: celery -A app.core.tasks.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dbproductividad:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - dbproductividad
    networks:
      - productivity-net

volumes:
  pgdata:

networks:
  productivity-net:
    driver: bridge
  traefik-public:
    external: true
